acoular/acoular

- docs/source/requirements.txt
create requirements.txt to make readthedocs build process work
> Esarradj patch readthedocs

- .github/workflows/python-package.yml
This should hopefully fix the workflow for hatch based builds
> Update python-package.yml for `hatch`

- acoular/grids.py
> line_grid one off bug

- acoular/configuration.py
This is a dummy PR which is only here to use Windows and MacOS checks. This real MR happens on TUB Gitlab
> attempts to fix openblas overcommittment

- .github/workflows/python-package.yml
- acoular/tests/test_traj_beamformer_results.py
Another dummy PR for the tests
> Fix CleantTraj tests

- .github/workflows/tests.yml
- acoular/__init__.py
- acoular/configuration.py
- acoular/demo/acoular_demo.py
- acoular/fbeamform.py
- acoular/h5files.py
- pyproject.toml
* adds a test that `acoular_demo.py` runs as expected (fixes #130 ) 
* uses `importlib` to check if packages can be imported (without actually importing them) -> speeds up Acoular import by > 1s! (fixes #212 )
> Acoular demo + Import speed up

- acoular/calib.py
> Add comment about calibration factors

- .github/actions/setup-hatch/action.yml
- .github/workflows/tests.yml
- CITATION.cff
- README.md
- acoular/version.py
- acoular/xml/minidsp_uma-16.xml
- docs/source/news/index.rst
- pyproject.toml
- recipe.local/meta.yaml
* drops Python 3.7 support
* adjust Acoular version to 24.05
* updates What's new documentation
> Release preperation

- acoular/demo/acoular_demo.py
The demo will no longer write the synthesized time data to file.
The demo will print an ASCII if matplotlib is not available. 
Docstring error is corrected.
> Updates demo with ASCII map and gets rid of writing file

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/docs_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- CONTRIBUTING.md
starts with contribution guidelines:
* adds CONTRIBUTING.md (will be extended later)
adds templates for reporting:
* bugs
* problems with the documentation
* feature requests
* optionally: use a blank form
to inspect the templates go to `Files changes` and click on `View file`
> Issue templates

- .github/workflows/tests.yml
- acoular/__init__.py
- acoular/sdinput.py
- pyproject.toml
> make SoundDeviceSamplesGenerator always importable

- pyproject.toml
This tries to (temporarily) solve #278.
> temporary fix to tables numpy 2.0 incompatibility problem

- acoular/version.py
- docs/source/news/index.rst
- pyproject.toml
pre-release work for Acoular version 24.07
> make ready to release

- .github/workflows/checks.yml
- .github/workflows/cron_jobs.yml
* `all_green` was started on the cron job which resulted in errors 
* introduces `cron_jobs.yml` and cleans up `checks.yml`
> fix cron job

- README.md
- acoular/demo/acoular_demo.py
- acoular/fbeamform.py
- acoular/grids.py
- acoular/signals.py
- acoular/sources.py
- acoular/spectra.py
- acoular/tbeamform.py
- docs/source/get_started/index.rst
- docs/source/news/index.rst
- examples/benchmark/test_beamformerfreq.py
- examples/introductory_examples/example_3D_beamforming.py
- examples/introductory_examples/example_basic_beamforming.py
- examples/io_and_signal_processing_examples/example_filter.py
- examples/moving_sources_examples/example_rotating_point_source.py
- examples/tools/example_evaluate.py
- examples/tools/example_tools.py
- examples/wind_tunnel_examples/example_airfoil_in_open_jet_cmf.py
- examples/wind_tunnel_examples/example_airfoil_in_open_jet_freq_domain_methods.py
- examples/wind_tunnel_examples/example_airfoil_in_open_jet_steering_vectors.py
- examples/wind_tunnel_examples/example_sectors_and_integration.py
- tests/test_beamformer_results.py
Preparation to remove deprecated traits in version 25.01.
> set version date for deprecated traits

- examples/wind_tunnel_examples/example_airfoil_in_open_jet_cmf.py
- examples/wind_tunnel_examples/example_airfoil_in_open_jet_freq_domain_methods.py
- examples/wind_tunnel_examples/example_airfoil_in_open_jet_steering_vectors.py
- examples/wind_tunnel_examples/example_airfoil_in_open_jet_time_domain_methods.py
- examples/wind_tunnel_examples/example_sectors_and_integration.py
use urllib to download necessary data to run example files.
> download time and calibdata to cwd if not found

- acoular/grids.py
- asfarray() no longer supported by numpy 2.x
- replace by ndarray.astype()
> replace numpy.asfarray

- CITATION.cff
- docs/source/news/index.rst
- pyproject.toml
* remove platform support for linux only in pyproject.toml
> More platform compatibility when building docs

- docs/source/contributing/install.rst
- docs/source/contributing/quality.rst
- docs/source/news/index.rst
* add quotes in installation guide at Install dependencies
* add mention of the dependencies in pyproject.toml
* add explanation on how to test specific Python version only
> Update contribution guide

- acoular/fbeamform.py
- acoular/grids.py
- acoular/tbeamform.py
- docs/source/news/index.rst
- pyproject.toml
> fix use of deprecated attributes

- .github/workflows/tests.yml
- pyproject.toml
> Cov report

- acoular/tprocess.py
- docs/source/news/index.rst
> replace np.matlib.repmat with np.tile

- .github/PULL_REQUEST_TEMPLATE.md
- docs/source/news/index.rst
* adds a pull request template
> Pull request template

- .github/workflows/regtest_inspect.yml
- docs/source/news/index.rst
Adds workflow to inspect regression tests output
> inspect CI regtest outputs

- .github/workflows/regtest_inspect.yml
> hot fix regtest CI

- acoular/tools/__init__.py
- acoular/tools/helpers.py
- acoular/tools/utils.py
- docs/source/conf.py
- docs/source/literature/literature.bib
- docs/source/news/index.rst
- docs/source/plots/c_air.py
- tests/unittests/test_tools.py
* adds new function :meth:`~acoular.tools.helper.c_air` to calculate the speed of sound from temperature and humidity
closes #345
> Adds function to calculate the speed of sound in air

- acoular/configuration.py
- acoular/environments.py
- acoular/fbeamform.py
- acoular/fprocess.py
- acoular/process.py
- acoular/sdinput.py
- acoular/signals.py
- acoular/sources.py
- acoular/spectra.py
- acoular/tbeamform.py
- acoular/tprocess.py
- docs/source/news/index.rst
Replaces all occurrences of `Traits` with `Enum`, `Union`, `Map` or `Instance`
Closes #375
> Fix the use of Trait factory 

- pyproject.toml
> fix upper version bound

- acoular/tprocess.py
- docs/source/news/index.rst
Small fix in `AngleTracker` for a bug that was introduced in #276.
> Fix `AngleTracker`

- .github/actions/setup-hatch/action.yml
> remove hatch version pin

- .github/workflows/auto-assign_pull_request.yml
I hope this fixes the assignee bot :)
> only add assignee if no assignee has been added

- acoular/fbeamform.py
- acoular/grids.py
- acoular/signals.py
- acoular/sources.py
- acoular/spectra.py
- acoular/tbeamform.py
- docs/source/news/index.rst
Traits were removed from:
* Grid
* RectGrid3D
* PowerSpectra
* PointSource
* UncorrelatedNoiseSource
* SineGenerator
* BeamformerTime
* BeamformerBase
* PointSpreadFunction
#346
> Remove deprecated traits ending with version 25.01 (#346)

- acoular/process.py
- docs/source/news/index.rst
- examples/io_and_signal_processing_examples/example_sample_splitter_bufferhandling.py
- pyproject.toml
* see title
* append doctest coverage to overall coverage
* improve SampleSplitter documentation
closes #341
> Enable varying block buffer sizes within SampleSplitter

- acoular/process.py
- acoular/signals.py
- acoular/sources.py
- acoular/tbeamform.py
- acoular/tprocess.py
`__class__` already influences the digest calculation, hence, it is redundant.
Related #385
> Remove `__class__` from digest dependencies

- acoular/grids.py
> Merge grid

- examples/moving_sources_examples/example_rotating_point_source.py
I encountered some problems with self-overwriting figures (which is solved by changing the figure numbers)
> fix plot numbers

- acoular/version.py
- docs/source/news/index.rst
Final changes before the new Acoular version is released.
> update version number

- acoular/trajectory.py
- docs/source/news/index.rst
- examples/moving_sources_examples/example_rotating_point_source.py
New docstrings for trajectory.py.
> docstrings for trajectory.py

- acoular/spectra.py
> reintroduce time_data trait

- acoular/grids.py
- acoular/trajectory.py
- docs/source/api_ref/index.rst
- docs/source/conf.py
- docs/source/literature/literature.bib
- docs/source/news/index.rst
- examples/moving_sources_examples/example_rotating_point_source.py
- examples/wind_tunnel_examples/example_sectors_and_integration.py
New docstrings for grids.py
#216
> docstrings for grids.py

- acoular/microphones.py
- docs/source/news/index.rst
docstring for microphones.py
#216
> docstrings for microphones.py

- acoular/environments.py
- docs/source/news/index.rst
* revise docstring for environments.py
#216
> docstrings for environments.py

- acoular/spectra.py
- docs/source/news/index.rst
docstrings for spectra.py
#216
> docstrings for spectra.py

- README.md
- acoular/demo/acoular_demo.py
- docs/source/get_started/index.rst
This amends PR #427
closes #373
> Right handed coordinate system for demo, readme and getting started

- docs/source/install/index.rst
- docs/source/news/index.rst
* add known issue sections to install guide
> Add known issues section

- .github/workflows/conda.yml
- docs/source/news/index.rst
- recipe.local/meta.yaml
> fix version, extend CI

- acoular/signals.py
- docs/source/literature/literature.bib
- docs/source/news/index.rst
Add new docstings to signals.py.
#216
> docstrings for signals.py

- acoular/sources.py
- docs/source/news/index.rst
* new docstrings for sources.py
#216
> docstrings for sources.py

- acoular/process.py
- docs/source/news/index.rst
* revise docstrings for process.py
#216
> docstrings for process.py

- CITATION.cff
- acoular/version.py
- docs/source/news/index.rst
> Release prep

- acoular/grids.py
- acoular/microphones.py
- docs/source/news/index.rst
Add comments for missing units in Grids and MicGeom.
#467
> DOCS: Meter unit comments for `Grid`s and `MicGeom`

- acoular/tools/helpers.py
- docs/source/news/index.rst
- examples/wind_tunnel_examples/example_airfoil_in_open_jet_cmf.py
- examples/wind_tunnel_examples/example_airfoil_in_open_jet_freq_domain_methods.py
- examples/wind_tunnel_examples/example_airfoil_in_open_jet_steering_vectors.py
- examples/wind_tunnel_examples/example_airfoil_in_open_jet_time_domain_methods.py
- examples/wind_tunnel_examples/example_sectors_and_integration.py
- Add helper function for downloading and/or finding examples data in the "data" directory
- Apply helper function in airfoil examples
> Generalize data import in airfoil examples

- acoular/sources.py
- docs/source/news/index.rst
> fix bug in PointSource when start silently crashes for some values
