acoular/acoular

examples/example1.py
When plotting result maps for different beamformers in frequency domain, the vertical axis were inverted.
=> Axis Y inverted

MANIFEST.in, setup.cfg
The terms of the BSD 3 Clause license require the license text be included with all copies of the software.
=> Include license file in sdists and wheels

.travis.yml
* Removes python 3.6, 3.7 for windows from Travis because of problems with pytables installation we cannot solve.
* Adds python 3.9 for OSX to Travis (works now with some additional pre-install support)
=> updates travis for win 3.6, 3.7

.github/workflows/github.yml
I just realized that labels were not correctly enforced by the CI job, because CI is not failing for all the new PRs. This one should fix it now.
=> fix `enforce-label` job

.github/actions/setup-hatch/action.yml, .github/workflows/github.yml, .github/workflows/tests.yml, docs/source/install/index.rst, pyproject.toml
Acoular is now compatible with Python version 3.12
* extend tests to 3.12
* use Python 3.12 as default for CI setup
=> add support for Python 3.12

.github/workflows/pypi.yml, .github/workflows/testpypi.yml, README.md, pyproject.toml
* uses hatch to build wheel and tarball
* adds CI workflows to build and deploy to TestPyPI and PyPI 
* fixes some typos and problems with links and images in README.md
* successful test publishing on TestPyPI -> https://test.pypi.org/project/acoular/ (I had to temporarily use a different version number, because after the upload the respective version is blocked and cannot be used again)
One thing I wasn't sure about was how we should handle it is what the tarball archive needs to include. Probably, the package could be smaller if we exclude some directories such as the tests directory for example. 
One flaw is that the installation with testpypi does not work out of the box, as some package distributions that Acoular depends on are not on TestPyPI. Therefore I had to check locally if the …
=> CI for TestPyPI and PyPI

acoular/environments.py
Adds new traits to `OpenJet` and `SlotJet` to adjust the length of flow establishment zone if needed.
Also closes #234 - it turned out that there is no need of unit vectors with the present code.
=> Adds flow establishment length traits

acoular/fbeamform.py, tests/test_beamformer_results.py
This addresses several issues by reworking some basic mechanics of `BeamformerBase`. In `BeamformerBase` and all derived classes, the result is computed per frequency. As the computations are quite expensive especially for advanced methods, it is inefficient to compute the result for any frequency that is not needed or required in the end. So far, this was controlled by `ind_low` and `ind_high` attributes of the `freq_data` attribute to `BeamformerBase` which lead to problems.  This closes #151 
by introducing a mechanism which computes only for those frequencies that are actually needed when then `result` attribute is queried using the index operator []:
- new private helper class `LazyResultArray` which controls the computation
- `_calc` method replaces 'calc' method
- `BeamformerBase` …
=> Implement a lazy result array for BeamformerBase derived classes

.github/actions/setup-conda/action.yml, .github/workflows/conda.yml, .github/workflows/labeler.yml
This change allows to upload the built conda package to anaconda.org
Upload will only take place if a workflow is started manually from the master branch
=> automate conda upload

.github/workflows/github.yml
Hopefully fixes labeler CI. (see https://github.com/yogevbd/enforce-label-action/issues/27). Current PR is stuck and requires making a dummy commit, even after label assignment. (see PR #316 )
=> add edited labeler to types

acoular/base.py, acoular/fbeamform.py, acoular/fprocess.py, acoular/process.py, acoular/spectra.py, acoular/tools/helpers.py, acoular/tprocess.py, tests/test_classes.py
again closes: #309 
* Fix newly introduced deprecation warnings in tests
* use pytest instead of unittests in `test_classes.py`
* actively deprecate the use of the `beamformer` trait
* loose deprecation policy (newly introduced DeprecationWarnings will take effect three releases after introduction)
=> Fix deprecation

acoular/fbeamform.py, acoular/fprocess.py, acoular/grids.py, acoular/process.py, acoular/signals.py, acoular/sources.py, acoular/spectra.py, acoular/tools/aiaa.py, acoular/tprocess.py, acoular/trajectory.py, docs/source/news/index.rst
- Refactors the `depends_on` keys to always be a list of strings. Before, `'a, b, c'` was used alongside `['a', 'b', 'c']`. Both are equivalent as per the [traits docs](https://docs.enthought.com/traits/traits_user_manual/listening.html#semantics).
=> Refactor `depends_on` dependencies

docs/source/conf.py, docs/source/news/index.rst
adds intersphinx connection for Python, SciPy and NumPy documentation.
One can now use for example 
```
:class:`numpy.ndarray`
``` 
for cross-linking, which then renders as:
=> Intersphinx

.github/labeler.yml, docs/source/news/index.rst
Stops the docs label from being added, if `docs/news/index.rst` is edited.
=> Fix labeler

acoular/configuration.py
Prevents premature loading of Numpy, so that Acoular has the chance to run in parallel 
Closes #412
- [-] I have updated the [What's new](https://www.acoular.org/news/index.html) section the the [documentation](https://github.com/acoular/acoular/blob/master/docs/source/news/index.rst) explaining my changes.
- [-] I have appended myself to the [CITATION.cff](https://github.com/acoular/acoular/blob/master/CITATION.cff) file.
=> Prevents numpy from premature loading

.ruff.toml, acoular/environments.py, docs/source/news/index.rst, tests/cases/test_environments_cases.py, tests/unittests/test_classes.py, tests/utils.py
- Adds a test that recursively ensures that any `Property` trait that is referenced by `depends_on` in another `Property` trait `depends_on` something.
- ~Refactors the `depends_on` keys to always be a list of strings. Before, `'a, b, c'` was used alongside `['a', 'b', 'c']` but now the latter is needed for the test to pass. Both are equivalent as per the [traits docs](https://docs.enthought.com/traits/traits_user_manual/listening.html#semantics).~
- Updates the `ruff` linting rules to deactivate `FIXME`
- Removes `noqa:TDXXX` and fixes them (proper `# TODO:` formatting)
- Turns `FlowField` into an abstract class, removes `FlowField.v` method, and removes `FlowField` from regression tests.
- New Issues #418, #419, #420 for remaining bugs the new test found
Closes #359
=> Test traits dependencies

acoular/aiaa/aiaa.py, acoular/version.py
Base class MicGeom uses `_import_mpos`. This method should be overwritten by the AIAA benchmark class instead of `import_mpos`
=> fixes import error

.github/actions/setup-conda/action.yml
Removes the installation step for `conda-verify` from the GitHub Actions workflow for setting up Conda. This change simplifies the workflow by eliminating an unused dependency.
=> remove conda verify

acoular/sources.py, docs/source/news/index.rst
Simulation of microphone signals in the presence of moving sources is very slow. This PR introduces block-wise processing in `MovingPointSource`, resulting in approx. 100-fold speedup over the old sample-wise processing.
=> block-wise processing in MovingPointSource

docs/source/news/index.rst, pyproject.toml
this PR excludes scipy 1.16 from the dependencies as it contains a bug affecting `scipy.signal.tf2sos` , see https://github.com/scipy/scipy/issues/23221
=> exclude scipy 1.16

docs/source/gen_rst.py, examples/wind_tunnel_examples/example_airfoil_in_open_jet_cmf.py, examples/wind_tunnel_examples/example_airfoil_in_open_jet_freq_domain_methods.py, examples/wind_tunnel_examples/example_airfoil_in_open_jet_steering_vectors.py, examples/wind_tunnel_examples/example_sectors_and_integration.py
There was no issue with `gen_rst.py` in regards to the `urllib.request` syntax. However, I found an unused import that we can remove. 
I've replaced `import urllib` with `import urllib.request` in the relevant examples. So #479 can be closed.
#479
=> remove unused import

tests/unittests/test_integrate.py
I looked into why we didn't catch #481 in our tests in the first place. It turns out that we always calculate the results beforehand and that the fixture scope is too broad such that the cached results from previous test runs mask this behaviour.
The test duration is now increased slightly. Not sure what we want to do here, it is the classical dilemma of fast vs. feasible...
=> modify test to catch fixed case

acoular/tprocess.py, docs/source/news/index.rst, tests/cases/test_generator_cases.py, tests/utils.py
- Implements `max_val` attribute that can be used to achieve consistent scaling.
- Avoids double computation of `source.result` by storing the result in the case that `max_val` is `None` and the maximum needs to be computed.
- Adds a warning, if `sample_freq` is not a whole number. Before, it was silently rounded in the `wave` module.
- Adds `encoding` attribute to allow also `uint8` and `int32` PCM formats. `uint24` would be straightforward to add in the future but I would not add it unless there is serious demand by the user base.
- now adds a `result` generator to `WriteWAV` that writes to file and passes through the data.
- removes `WriteWAV` from the blacklist in `test_result_generator`
- adds a warning if clipping occurs
Closes #126 #478 #473 
Related #382
=> rework `WriteWAV`

acoular/grids.py, acoular/microphones.py, docs/source/news/index.rst
The notes about the unit system stood in custom sections. These were not recognized and caused warnings. The unit system notes are now in the Note sections.
=> Move unit system sections to Note sections

.ruff.toml, acoular/h5cache.py, docs/source/news/index.rst
- add missing docstrings to public methods in ``h5cache.py``
#216
Closes #506
=> Fix docstrings for ``h5cache.py``

.ruff.toml, acoular/fbeamform.py, docs/source/news/index.rst
- fix the docstrings in ``fbeamform.py`` for linting errors
#216
Closes #505
---
**This PR is _not_ a proper revision of the docstrings, it only fixes them as far as meeting linting requirements. There still needs to be a compete overhaul of the docstrings.**
---
=> Fix docstrings for ``fbeamform.py``

.ruff.toml, acoular/h5files.py, docs/source/news/index.rst
- add missing docstings to public methods in ``h5files.py``
- remove ``pass`` statements to prevent linting errors
#216
Closes #504
=> Fix docstrings for ``h5files.py``
